import StyledComponentsRegistry from "@/lib/AntdRegistry";
import {getLocaleInfo} from "@/app/_func/server";
import LocaleContextManager from "@/component/context/localeContext";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({children,}) {
    const {locale, dictionary} = await getLocaleInfo()
    return (
        <html lang="en">
        <body>
        <StyledComponentsRegistry>
            <LocaleContextManager locale={locale} dictionary={dictionary}>
                {children}
            </LocaleContextManager>
        </StyledComponentsRegistry>
        </body>
        </html>
    )
}
