import {Inter} from 'next/font/google'
import Header from "@/component/common/Header";
import Footer from "@/component/common/Footer";
import './global.css';
import styles from "./layout.module.css";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div>
            <Header></Header>
            <div className={styles.main}>
                <div className={styles.content}>
                    {children}
                </div>
            </div>
            <Footer></Footer>
        </div>
        </body>
        </html>
    )
}
