import {Inter} from 'next/font/google'
import Header from "@/component/common/Header";
import Footer from "@/component/common/Footer";
import './global.css';
import styles from "./layout.module.css";
import StyledComponentsRegistry from "@/lib/AntdRegistry";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={styles.main}>
            <div className={styles.header}>
                <div className={styles.header_content}>
                    <StyledComponentsRegistry>
                        <Header/>
                    </StyledComponentsRegistry>
                </div>
            </div>
            <div className={styles.body}>
                <div className={styles.body_content}>
                    {children}
                </div>
            </div>
            <Footer/>
        </div>
        </body>
        </html>
    )
}
