import {Inter} from 'next/font/google'
import Header from "@/component/common/Header";
import Footer from "@/component/common/Footer";
import './global.css';
import styles from "./layout.module.css";
import StyledComponentsRegistry from "@/lib/AntdRegistry";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    // let s = usePathname();
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={styles.main}>
            <StyledComponentsRegistry>
                <div className={styles.header}>
                    <div className={styles.header_content}>
                        <Header/>
                    </div>
                </div>
                <div className={styles.body}>
                    {children}
                </div>
                <Footer/>
            </StyledComponentsRegistry>
        </div>
        </body>
        </html>
    )
}
